# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
sudo: required
cache: packages

addons:
  apt:
    packages:
      - libhdf5-serial-dev
      - libgdal-dev
      - libproj-dev

before_install:
  - wget http://hydromad.catchment.org/src/contrib/hydromad_0.9-26.tar.gz
  - R CMD install hydromad_0.9-26.tar.gz
  - cd /home/travis/build/cvitolo/curvenumber

r_github_packages:
  - jimhester/covr

after_success:
  - Rscript -e 'covr::codecov()'
